
export const EMAIL_ENCRYPTION_TYPES = {
	SSL: 'SSL',
	TLS: 'TLS',
	NONE: 'None',
};

export const EMAIL_CONFIG_FORM_FIELDS = {
	EMAIL_ENCRYPTION_TYPES: EMAIL_ENCRYPTION_TYPES,
	DEFAULT_SMTP_PORT: 587,
	DEFAULT_IMAP_PORT: 993,
	DEFAULT_SMTP_ENCRYPTION: EMAIL_ENCRYPTION_TYPES.SSL,
	DEFAULT_MESSAGE_PER_DAY: 200,
	DEFAULT_TIME_GAP: 60
};